heat_template_version: 2015-10-15

description: Shared Resources for Labs

parameters:
  stack_name:
    label: "Stack Name Prefix"
    description: stack name for labs
    default: "demo"
    type: string

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
     name:
       str_replace:
         template: "%heat_stack_prefix%-shared-keypair"
         params:
           "%heat_stack_prefix%": { get_param: stack_name  } 
     save_private_key: True

outputs:
  private_key:
    description: Private Key
    value: { get_attr: [ keypair, private_key ] }
  keypair:
    description: blah
    value:
       str_replace:
         template: "%heat_stack_prefix%-shared-keypair"
         params:
           "%heat_stack_prefix%": { get_param: stack_name  }
