heat_template_version: 2013-05-23

description: Shared Resources for Labs

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: "%heat_stack_prefix%-shared-keypair"
          params:
            "%heat_stack_prefix%": { "Fn::Select": [ "0", { "Fn::Split" : [ "-", { get_param: "OS::stack_id" } ] } ] }
      save_private_key: True

outputs:
  private_key:
    description: Private Key
    value: { get_attr: [ keypair, private_key ] }
